spring:
  application:
    name: bookmyshow-backend
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://34.132.144.182:5432/bookmyshow} 
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:Postgresql-personal01}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    open-in-view: false
  # flyway:
  #   enabled: true
  #   locations: classpath:db/migration

server:
  port: ${PORT:8081}

app:
  jwt-secret: ${JWT_SECRET:m8Qz9eWz7Z8m6lG7vJbP3WvNf8U6tYkR9sQx2DkL1pM=}
  jwt-expiration-ms: 86400000
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  stripe-key: ${STRIPE_KEY:sk_test_51S27ljRDTsIiaaDzmxuMv59rBjR4sIgzmTvGcebnBGIurRceo3d7JWCTbZ1G31pUwJ3YHsC9gjK4D0n7lIT7yonw00kP1g3RbU}
  resend-api-key: ${RESEND_API_KEY:re_8xuRQ1zd_49fSopkBS9CwT8YDVSKiJsmW}
